### ISSUE TITLE
Styling doesn't nest well

### ISSUE THREAD

**Issue by Binero** [mitsuhiko/console#106]
I tried to do this:

```rs
style(format!("No mod named {} found", style(name).bold())).yellow()
```

I expected this to print out a fully yellow line, but instead I got:

![image](https://user-images.githubusercontent.com/6867251/146618458-168e946e-e800-45ed-80f0-ccb38bc27144.png)

**Comment by pksunkara** [comment]
Yeah, every style clears the style at the end. So, you would have to build it properly instead of letting side effects take control (which is what you are proposing).
