### ISSUE TITLE
emoji goodness for linux

### ISSUE THREAD

**Issue by arabidopsis** [mitsuhiko/console#18]
Any chance of getting some Emoji goodness on linux? I know it's patchy but it is there. Something along the lines of:
```
#[cfg(target_os = "linux")]
lazy_static! {
    static ref is_lang_utf8 : bool = {
        match ::std::env::var("LANG") {
            Ok(lang) => lang.to_uppercase().ends_with("UTF-8"),
            _ => false
        }
    };
}
pub fn wants_emoji() -> bool {
    cfg!(target_os = "macos") || ( cfg!(target_os = "linux") && *is_lang_utf8 )
}
```

**Comment by arabidopsis** [comment]
Just to clarify... I haven't presented a pull request because I know from your work with click
that you're probably a world expert on Unicode and the terminal :). I have *no idea*  how best to do this.

**Comment by reillysiemens** [comment]
It would be useful to have emoji support on platforms other than macOS. Fedora, for example, has supported emoji in terminals for some time now. Is there a barrier besides just a pull request to implementing something like the suggestion from @arabidopsis?

**Comment by ahmed-masud** [comment]
Actually your approach is more appropriate than the original test `cfg!(target_os = "macos")`... since any posix.2 compliant system should honor the LANG setting.
 
http://www.unicode.org/emoji/charts/full-emoji-list.html

**Comment by mitsuhiko** [comment]
The problem is that I could not find a way to figure out if emojis work on the terminal on linux or not. It just happens that emojis work on all macos terminals currently.

**Comment by craftytrickster** [comment]
I think that the OP's solution is a good one. You would not be altering the support on macos, keeping it intact. With this approach, on linux, you are correctly detecting emojis the vast majority of the time (in my experience, 100% of the terminals that have LANG set with UTF8 support emojis).

**Comment by pksunkara** [comment]
Sure. Will merge the PR if sent

**Comment by craftytrickster** [comment]
Will open shortly, just need to test
