### ISSUE TITLE
Term clear_screen panics on windows 10

### ISSUE THREAD

**Issue by DevinR528** [mitsuhiko/console#24]
Just to be sure this should work on windows 10 in cmd.exe?

```rust
let t = Term::stdout();
t.write_line("hello")?;
t.clear_screen()?;
``` 
I get a panic caused by multiplication overflow from windows_term.rs line 120 in my case x=120, y=9001.  If this is a bug on windows and not just me I can give you a bit more info.

Thanks!

**Comment by dalance** [comment]
This seems to be the same issue as #17.

@mitsuhiko Could you review and merge #17? I think this is a critical issue.

**Comment by mitsuhiko** [comment]
Merged!

**Comment by dalance** [comment]
Thank you for your quick response.
Please bump version.

**Comment by dalance** [comment]
Thanks!
