### ISSUE TITLE
illumos support

### ISSUE THREAD

**Issue by papertigers** [mitsuhiko/console#31]
I have had dcuddeback/termios-rs#21 open on termios-rs for 7 months and it doesn't look there has been any activity for almost a year on that repo.  It's been a pain to deal with anything on illumos/solaris that uses console due to the need to point Cargo.toml at my custom version.  Would you be opposed to a PR that changes the unix dependency on termios-rs to point to a fork of that repo with my change for illumos/solaris and leave all other unix's pointing at the official repo.  One example of where dealing with this has been painful is when building "bat".

**Comment by mitsuhiko** [comment]
@papertigers i would be happy to just add whatever we need form termios into this crate. Can't be that much code.

**Comment by papertigers** [comment]
termios changes got merged.  Closing
