### ISSUE TITLE
Create a Term from arbitrary Read and Write pair

### ISSUE THREAD

**Issue by argv-minus-one** [mitsuhiko/console#34]
Currently, a `Term` can only be created from `stdin` and either `stdout` or `stderr`. This covers the most common case, but is rather inflexible.

The issue I'm running into is that I can't mock user interaction with my program (which uses dialoguer) in a test case, because there's no way to create a `Term` that's connected to mock I/O streams.

Another possible use case is interacting with a user through a socket. For instance, a Rust program might contain an embedded SSH server and interact with users that way.

Please consider allowing the creation of `Term`s connected to arbitrary `Read` and `Write` implementations, or at least arbitrary file descriptors/handles.

**Comment by mitsuhiko** [comment]
I would accept a patch for this.

**Comment by stuhood** [comment]
Related: I'd like to be able to open for an arbitrary `RawFd`... `Term` currently implements `AsRawFd`, so perhaps the relevant bounds here would be `Read + Write + AsRawFd`?

I can take a swing at the patch if so.

**Comment by pksunkara** [comment]
Go ahead.

**Comment by stuhood** [comment]
Thank you. Will try to start this next week (unless someone beats me to it!)

**Comment by stuhood** [comment]
Have started.

**Comment by stuhood** [comment]
Hey folks! Would appreciate review on https://github.com/mitsuhiko/console/pull/93 when you get a chance.
