### ISSUE TITLE
[Feature Reqest] Get cursor position

### ISSUE THREAD

**Issue by Zooce** [mitsuhiko/console#38]
I'm running into an issue where '\r' is being mapped to '\n' when running a program in `urxvt` via Cygwin. My idea to work around this is to just set the cursor position to column 0 of the current line. However, I can't get the current line with `console`.

Ideal usage:
```rust
let mut term = console::Term::stdout();
let (_, y) = term.get_cursor_pos()?;
term.move_cursor_to(0, y)?;
```

Possible Alternatives:
1. Add `move_cursor_left` and `move_cursor_right`. This complements the already existing functions `move_cursor_up` and `move_cursor_down`. Although in the use case I'm talking about, there's still extra work the caller has to do if they want to move "all the way" left or right.
2. For convenience add, `move_cursor_to_start` and `move_cursor_to_end` (or something similar). Not sure on the naming here, but the idea would be to have functions that move the cursor either to the very beginning of the current line or the very end.

**Comment by pnmtjonahen** [comment]
See my PR

**Comment by pksunkara** [comment]
Merged the PR
