### ISSUE TITLE
`show_cursor` also clears the screen

### ISSUE THREAD

**Issue by Zooce** [mitsuhiko/console#39]
The `show_cursor` command does way more than just show the cursor (`[?25h`). I think this should be changed just to show the cursor, and nothing else, so it matches the behavior of its counterpart, `hide_cursor`.

Also, see #25

**Comment by DevinR528** [comment]
Yup you are right at the time I was using it the very next thing I would always do was clear the screen.

Do you have any idea what the escape code would be everything I found said `[?25h` was the way to show the cursor?
