### ISSUE TITLE
[feature request] support for target `wasm32-wasi`

### ISSUE THREAD

**Issue by mash-graz** [mitsuhiko/console#41]
@mitsuhiko

right now `console` only supports `unix` and `windows` targets but nothing else.
this makes it rather difficult to compile rust applications depending on this crate to webassembly resp. WASI e.g. for use in [webassembly.sh](https://webassembly.sh/)

do you see any simple workaround for this issue?

**Comment by mitsuhiko** [comment]
@mash-graz can you make a patch that explicitly covers wasm targets? I think I won't have time to work on this atm but it should be fairly simple to patch.

**Comment by mash-graz** [comment]
@mitsuhiko
yes -- i'll try to find a solution or at least acceptable workaround...

it seems to be a open question, how we should handle this terminal related differences in an adequate and compatible manner. this doesn't only concern your crate but also [termios-rs](https://github.com/dcuddeback/termios-rs) and similar stuff. (see: https://github.com/WebAssembly/WASI/issues/42)

**Comment by mitsuhiko** [comment]
Yeah. Right now I think the goal would just be to make it compile and have some reasonable default behavior.

**Comment by wucke13** [comment]
Hi, came here to open up an issue about this. 

When in doubt, I guess using the TERM variable could help gathering information. But then again, outputting ANSI escape sequences for colors etc. should be sufficient, the new Windows Terminal App will probably support them too.

**Comment by mash-graz** [comment]
it's in fact a rather complicated issue, because the wasi core developers want to avoid malicious control sequences on TTY output by rather restrictive precautions ...

see:  https://github.com/WebAssembly/WASI/issues/162, https://github.com/WebAssembly/WASI/issues/163, https://github.com/WebAssembly/WASI/issues/167
and  https://github.com/bytecodealliance/wasmtime/pull/684

but the main obstacle i would still see in the cat, that we can not realize unbuffered input on the wasi platform till now, because there is no posix `termio.h` interface or its counterpart on the windows side available. 

see: https://github.com/WebAssembly/WASI/issues/161

**Comment by mitsuhiko** [comment]
For now I made it compile.
