### ISSUE TITLE
Style renders incorrectly before and after running command

### ISSUE THREAD

**Issue by vallentin** [mitsuhiko/console#47]
This bug is two-fold. I assume it's the same bug, which just manifests itself in two different ways, depending on the terminal used.

1. Using Git Bash on Windows 10. Then using `.dim()` does not have any effect. However, after running a command e.g. `git diff` using `std::process::Command`, then `.dim()` has an effect.
2. On the other hand, using CMD or PowerShell, then after running the command, then the ANSI codes appear literally in the output.

The command being executed seem to be important, as changing the command to e.g. `cargo --version` or even `git --version`. Then 2. does not happen. However, then `.dim()` isn't "fixed" either.

## Git Bash

Notice the third  `.dim()` styled `Foo` is rendered the same as the first unstyled `Foo`.

**Without Changes:**

![dim](https://user-images.githubusercontent.com/17464404/73961436-db8b5c00-490c-11ea-885b-1b58448552fc.png)

**With Changes:**

![dim2](https://user-images.githubusercontent.com/17464404/73962447-c0b9e700-490e-11ea-8cbc-6b2c88639227.png)

## CMD

*Renders the same with and without changes, and renders the same in PowerShell.*

![dim-cmd](https://user-images.githubusercontent.com/17464404/73961637-463c9780-490d-11ea-987f-4c4830ec8b24.png)

## Minimal, Reproducible Example

```rust
// rustc 1.41.0 (5e1a79984 2020-01-27)
// cargo 1.41.0 (626f0f40e 2019-12-03)

use std::process::Command;

// console = "0.9.2"
use console::style;

fn main() {
    println!("Foo {} Baz", "Bar");
    println!("Foo {} Baz", style("Bar").cyan());
    println!("Foo {} Baz", style("Bar").dim());
    println!("Foo {} Baz", style("Bar").red());
    println!();

    // Renders incorrectly if git diff is executed
    Command::new("git").arg("diff").status().unwrap();

    // Has not effect
    // Command::new("cargo").arg("--version").status().unwrap();
    // Command::new("git").arg("--version").status().unwrap();

    println!("Foo {} Baz", "Bar");
    println!("Foo {} Baz", style("Bar").cyan());
    println!("Foo {} Baz", style("Bar").dim());
    println!("Foo {} Baz", style("Bar").red());
    println!();
}

```

**Comment by vallentin** [comment]
Potentially an upstream issue, in your other [clicolors-control](https://github.com/mitsuhiko/clicolors-control) crate.

**Comment by vallentin** [comment]
Manually calling `configure_terminal()` after having executed a command, fixes the CMD and PowerShell issue.

```rust
Command::new("git").arg("diff").status().unwrap();

clicolors_control::configure_terminal();
```

**Comment by mitsuhiko** [comment]
Closing this for https://github.com/mitsuhiko/clicolors-control/issues/15. Not sure if the underlying issue is resolvable but adding your own dependency to `clicolors_control` is I believe better than re-exporting more from there.
