### ISSUE TITLE
Wrapping with Windows Git Bash Shell

### ISSUE THREAD

**Issue by craigtmoore** [mitsuhiko/console#48]
Hello,

I'm having trouble with line wrapping when using bat in the Windows Git Bash Shell. Bat uses this library to work out the console width. I created [issue #824](https://github.com/sharkdp/bat/issues/824#issue-563287153) on their repo, but they said I should push it upstream. They identified this code fragment as the likely culprit.

https://github.com/mitsuhiko/console/blob/a999e34bbbf66886aa7420dc6e2d7cc264ade959/src/windows_term.rs#L77-L87

**Comment by sharkdp** [comment]
Minor correction: I don't think that anything is wrong with this code. I rather think that MinGW/Git Bash is not properly responding to this Windows API call for some reason.

**Comment by craigtmoore** [comment]
Ah ok, hm... I'll have to find that repo
