### ISSUE TITLE
read_key() does not recognize backspace

### ISSUE THREAD

**Issue by Shadoka** [mitsuhiko/console#49]
Hi,

on Win10 _read_key()_ does not return _Key::Backspace_ when pressing backspace.
Just running standard Win10-Console, no Git-Bash, PS or anything else.
Following code should loop as long as I am only pressing backspace, but terminates nonetheless:

[Small gist](https://gist.github.com/Shadoka/63b282739fb2ccc7d7b8f3c88774b42a)

console-version: 0.9.2
rust-version: 1.38.0

An unfortunate side effect is that _read_line_initial_text_ does not delete the last char but just sets the cursor one to the left.

**Comment by Shadoka** [comment]
I added an extra case for the character '\x08' in _read_single_key_ in _windows_term.rs_ [(see lines 15 & 16 in this gist)](https://gist.github.com/Shadoka/fa77cc437af9ab9060aa405d456a545d).
This seems to solve the issue for me.
The arrow keys seem to work fine, but for ESC I had to put in another case for '\x1B'.
I'm not particularly skilled in the usage of git (always worked with SVN on the job), but I can try to do a pull request, if you so wish.

**Comment by Shadoka** [comment]
Just went ahead and created a pull request => #50 

On a completely unrelated note:
Pressing Backspace when in _read_line_intial_text_ eventually leads to deletion of the initial text, which (atleast in my mind) is not what you want. Would it be alright to create another pull request with a method that respects this behaviour?

**Comment by mitsuhiko** [comment]
Merged the PR.
