### ISSUE TITLE
Order of width/height in Term::stdout().size() has changed

### ISSUE THREAD

**Issue by sharkdp** [mitsuhiko/console#58]
The order of width/height in the tuple output of `Term::stdout().size()` has changed from 0.10.0 to 0.10.1. I assume that this was not intentional. Otherwise, 0.10.1 breaks semver.

Edit: The docs for `size_checked` explicitly say *"the terminal size in rows and columns"*, so I guess rows should indeed be first.

The order is still "wrong" in 0.11.

see: https://github.com/sharkdp/bat/issues/955

Long-term, using a simple `struct` instead of a tuple would be a good idea IMO.

**Comment by pksunkara** [comment]
Yup, was a mistake. Thanks for catching it. I was trying to fix the compatibility stuff.
