### ISSUE TITLE
Term::size is broken on Windows

### ISSUE THREAD

**Issue by sharkdp** [mitsuhiko/console#60]
Since the update to the `terminal-size` crate, `Term::size` and `Term::size_checked` are broken on Windows due to https://github.com/eminence/terminal-size/issues/18

`Term::size_checked` returns `None` on interactive terminals. It returns `(1, 1)` if no terminal is attached to STDOUT.

Also, note that there is another change in behavior (which is probably good): After https://github.com/eminence/terminal-size/issues/18 has been fixed, `terminal-size` reports a terminal size which is larger by one in both height and width (https://github.com/eminence/terminal-size/blob/e9a708e15a5e582aad03855e40d1f41b6b01c5f0/src/windows.rs#L38-L39). The returned size is correct. The value returned by `console` 0.10 and before was too small.

**Comment by pksunkara** [comment]
Yup, it was one of the reasons I decided to delegate this to `terminal-size` crate. I saw the logic wasn't being maintained in this crate and knew that the above crate fixed the offset by 1 error. IMO It's better if the community focuses on fixing one crate instead and use it.
