### ISSUE TITLE
VS Code Terminal + clear_last_lines

### ISSUE THREAD

**Issue by forrestthewoods** [mitsuhiko/console#61]
Hi. I'm attempting to write an interactive console app for a toy project and am using `console`.

The problem comes from calling `term.clear_last_lines(n)` where `n` is larger than the number of visible lines. It produces an underflow exception. Curiously neither standalone `powershell.exe` nor `cmd.exe` have this issue. So I'm not sure what's special about VSCode. 

A workaround for the exception is change `move_cursor_up.rs move_cursor_up` from `csbi.dwCursorPosition.Y as usize - n` to `(csbi.dwCursorPosition.Y as usize).saturating_sub(n)`. But this doesn't actually clear the requested number of lines so it's not ideal.

**Comment by pksunkara** [comment]
But that's for windows console API. VScode uses the ansi escape code which is just normal. So, looks like VScode has issues when moving the cursor up more than the height of the terminal.
