### ISSUE TITLE
No emoji support inside of WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by SirWindfield** [mitsuhiko/console#70]
According to the source code, it checks if the `LANG` env ends with `UTF-8`. Mine does (`C.UTF-8`). It still prints out `false` when I run `console::Term::stdout().features().wants_emoji()`.

`console::Term::stdout().features().family()` reports `UnixTerm`. `console::Term::stdout().features().is_attended()` returns `true` as well. 

Not sure if this matters:
```rust
println!("{:#?}", term_intance.features());
Emoji: TermFeatures(
    Term {
        inner: TermInner {
            target: Stdout,
            buffer: None,
        },
        is_msys_tty: false,
        is_tty: true,
    },
)
```

**Comment by jheyens** [comment]
Am I guessing correctly that you are using v0.11.3 from crates.io?

That version does not yet look at $LANG and instead checks only whether it is running on MacOS (wants_emoji() == true) or not (otherwise).

The relevant code is here: https://github.com/mitsuhiko/console/blob/v0.11.3/src/unix_term.rs#L190

**Comment by SirWindfield** [comment]
Not entirely sure which version I used back then, should have checked it, sorry! I used the newest one though, I'm pretty sure.

**Comment by jheyens** [comment]
v0.11.3 is still the most recent version published to crates.io.

I am not involved with this project, though. We should ask @mitsuhiko whether he plans to release a new version soon.

**Comment by pksunkara** [comment]
It's only the LANG commit after 0.11.3. I was waiting for more commits before next version.

**Comment by jheyens** [comment]
I don't know, it's been two months and the code change is trivial. I don't see why this couldn't be v0.11.4.

I don't really mind though, I'm simply using `console = { git = "https://github.com/mitsuhiko/console.git"}` for now.

**Comment by SirWindfield** [comment]
The thing about semver versioning is the fact that you can release new features and patches with ease :) There speaks nothing against publishing even smaller changes/features :) Look at serde for example, `v1.0.113`. :)



> I don't really mind though, I'm simply using `console = { git = "https://github.com/mitsuhiko/console.git"}` for now.

That doesn't work for me sadly, as the crate is published on crates.io and you can't use git dependencies :(
