### ISSUE TITLE
Undeprecate is_term

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/console#86]
@pksunkara  can we undeprecate `is_term`? It's such a common operation and now you need to use a much more complex API to use it.

**Comment by pksunkara** [comment]
Okay, I thought you wanted to move everything to `features()` when I took over the code which is why I deprecated it.

**Comment by mitsuhiko** [comment]
I think it's fine to keep. I mostly noticed because indicatif started causing deprecation warnings when using latest console and I did not really like the upgrade experience :)
