### ISSUE TITLE
Redirecting stdout cause losing color for stderr

### ISSUE THREAD

**Issue by serbanrobu** [mitsuhiko/console#87]
This example works
```rust
eprintln!("This is {} neat", style("quite").cyan());
````
if I run `cargo run` but if I run `cargo run > /dev/null` the color don't work.

**Comment by serbanrobu** [comment]
I found a function for forcing colors in this case: https://docs.rs/console/0.14.0/console/fn.set_colors_enabled.html

**Comment by pksunkara** [comment]
Yeah, because we recognize that you don't have a TTY attached when you are piping to `/dev/null`
