### ISSUE TITLE
 Key::Enter not working on PowerShell

### ISSUE THREAD

**Issue by Morasiu** [mitsuhiko/console#9]
Hi,

I'm currently using Rust to write a console game and when I do:

```rust 
let key = term.read_key().ok();
    match key.unwrap() {
        Key::Char('q') => std::process::exit(0),
        Key::Enter => if *turn == 1 {
                *turn = 2; 
        } else {
            *turn = 1;
        },
        
        _ => ()
    }
```

Option *is key Enter* is never called. Neither with normal Enter or Right Enter.

I'm using Windows 10 with PowerShell (I know Windows bleh...)

**Comment by mitsuhiko** [comment]
I would love to get a patch for this :)

**Comment by paul-caron** [comment]
I also am on windows 10 and when using term.read_key() and pressing the arrows, it gives the Key::Unkown. The Enter when pressed gives Char('\r').
