### ISSUE TITLE
Publish is_term undeprecation to crates.io

### ISSUE THREAD

**Issue by dtolnay** [mitsuhiko/console#94]
https://github.com/mitsuhiko/console/commit/f61351bb3d81062a85e14b58ff26c88855dfbc2e was merged to master last month, closing #86, but was never published to crates.io. Builds of downstream crates like `indicatif` are still printing deprecation warnings and the method still appears as deprecated in docs.rs documentation.

```console
warning: use of deprecated associated function `console::Term::is_term`: Use features().is_attended() instead
   --> /git/tmp/indicatif/src/progress.rs:138:65
    |
138 |             ProgressDrawTargetKind::Term(ref term, ..) => !term.is_term(),
    |                                                                 ^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

![Screenshot from 2021-03-06 22-17-42](https://user-images.githubusercontent.com/1940490/110230997-c85d0e00-7ec9-11eb-93a2-168c299bad52.png)

**Comment by pksunkara** [comment]
Done with 0.14.1
